import Phaser from 'phaser';
import type {FighterRuntime} from '../fighters/Fighter';
import type {UltimateDefinition} from '../data/ultimateDefinitions';
export class UltimateCutInManager{
 isActive=false;private objects:Phaser.GameObjects.GameObject[]=[];private timers:Phaser.Time.TimerEvent[]=[];
 constructor(private scene:Phaser.Scene){}
 private keep<T extends Phaser.GameObjects.GameObject>(o:T){this.objects.push(o);return o;}
 private style(fid:string){const m:Record<string,{overlay:number,title:string,bubble:number,shake:number}>={alien:{overlay:0x071a0b,title:'#63ff7e',bubble:0x102f18,shake:.008},doge:{overlay:0x4a3900,title:'#ffe34f',bubble:0x3c3000,shake:.012},ya:{overlay:0x392536,title:'#ffb6e7',bubble:0xffffff,shake:.006},tempura:{overlay:0xffffff,title:'#111111',bubble:0xffffff,shake:.014},goblin:{overlay:0x451a40,title:'#ff9de1',bubble:0xffd7f1,shake:.008},salad:{overlay:0x283813,title:'#dfff6e',bubble:0xf3ffd4,shake:.014},wizard:{overlay:0x170b28,title:'#c778ff',bubble:0x221337,shake:.009},blade:{overlay:0x101b2b,title:'#79c9ff',bubble:0x17263b,shake:.012},pink:{overlay:0x3c0c2a,title:'#ff70c6',bubble:0xffd3ec,shake:.014},sauce:{overlay:0x382314,title:'#f0bd79',bubble:0x6b432b,shake:.013},scared:{overlay:0x07172a,title:'#9ed7ff',bubble:0xeaf7ff,shake:.012},ok:{overlay:0x0c0c0c,title:'#e7b74c',bubble:0x171717,shake:.013}};return m[fid]??m.alien;}
 start(owner:FighterRuntime,def:UltimateDefinition,onComplete:()=>void){if(this.isActive)return false;this.abort();this.isActive=true;const s=this.style(def.fighterId);const dark=this.keep(this.scene.add.rectangle(640,360,1280,720,0x000000,0).setDepth(200));const bg=this.keep(this.scene.add.image(640,360,def.backgroundTexture).setDepth(201).setAlpha(0).setScale(1.05));const tint=this.keep(this.scene.add.rectangle(640,360,1280,720,s.overlay,.22).setDepth(202).setAlpha(0));const char=this.keep(this.scene.add.image(owner.side===1?370:910,690,def.cutInCharacterTexture).setOrigin(.5,1).setDepth(203).setAlpha(0).setScale(.72));const bx=owner.side===1?760:520,by=230;const bubble=this.keep(this.scene.add.rectangle(bx,by,540,118,s.bubble,.96).setStrokeStyle(6,def.fighterId==='tempura'?0x111111:0xffffff,1).setDepth(204).setScale(0));const tailX=owner.side===1?bx-245:bx+245;const tail=this.keep(owner.side===1?this.scene.add.triangle(tailX,by+66,0,0,58,0,0,58,s.bubble,.96):this.scene.add.triangle(tailX,by+66,0,0,-58,0,0,58,s.bubble,.96));tail.setDepth(204).setScale(0);const voice=this.keep(this.scene.add.text(bx,by,def.voiceText,{fontFamily:'Impact, sans-serif',fontSize:def.voiceText.length>20?'27px':'33px',color:def.fighterId==='tempura'?'#111111':'#ffffff',stroke:'#000000',strokeThickness:4,align:'center',wordWrap:{width:500}}).setOrigin(.5).setDepth(205).setAlpha(0));const title=this.keep(this.scene.add.text(640,570,def.ultimateName,{fontFamily:'Impact, sans-serif',fontSize:'66px',color:s.title,stroke:'#000000',strokeThickness:10,align:'center'}).setOrigin(.5).setDepth(206).setAlpha(0).setScale(1.6));const flash=this.keep(this.scene.add.rectangle(640,360,1280,720,0xffffff,1).setDepth(207).setAlpha(0));
 this.scene.tweens.add({targets:dark,alpha:.66,duration:90});this.scene.tweens.add({targets:bg,alpha:1,scale:1,duration:180,ease:'Quad.easeOut'});this.scene.tweens.add({targets:tint,alpha:.22,duration:180});this.scene.tweens.add({targets:char,alpha:1,x:owner.side===1?420:860,duration:210,ease:'Back.easeOut'});
 this.timers.push(this.scene.time.delayedCall(210,()=>{if(!this.isActive)return;this.scene.tweens.add({targets:[bubble,tail],scale:1.15,duration:80,yoyo:true,onComplete:()=>{bubble.setScale(1);tail.setScale(1);}});voice.setAlpha(1);}));
 this.timers.push(this.scene.time.delayedCall(390,()=>{if(!this.isActive)return;title.setAlpha(1);this.scene.tweens.add({targets:title,scale:1,duration:190,ease:'Back.easeOut'});this.scene.cameras.main.shake(110,s.shake);flash.setAlpha(.7);this.scene.tweens.add({targets:flash,alpha:0,duration:100});if(def.fighterId==='alien'||def.fighterId==='pink')this.scene.tweens.add({targets:bg,x:{from:636,to:644},yoyo:true,repeat:5,duration:35});}));
 const duration=Phaser.Math.Clamp(900+def.voiceText.length*32,def.minCutInMs,def.maxCutInMs);this.timers.push(this.scene.time.delayedCall(duration-230,()=>{if(!this.isActive)return;flash.setAlpha(.72);this.scene.tweens.add({targets:[bg,char,bubble,tail,voice,title,tint],alpha:0,duration:190});this.scene.tweens.add({targets:flash,alpha:0,duration:210});}));this.timers.push(this.scene.time.delayedCall(duration,()=>{if(!this.isActive)return;this.finish();onComplete();}));return true;
 }
 private finish(){for(const t of this.timers)t.remove(false);this.timers=[];for(const o of this.objects)(o as any)?.destroy?.();this.objects=[];this.isActive=false;this.scene.cameras.main.resetFX();}
 abort(){if(!this.isActive&&this.objects.length===0)return;this.finish();}
}
