export type PoseId = `${number}`;

export type PoseRectSpec =
  | {kind:'normalized';x:number;y:number;width:number;height:number;captionTrim?:number}
  | {kind:'pixel';x:number;y:number;width:number;height:number;captionTrim?:number}
  | {kind:'custom-merged';x:number;y:number;width:number;height:number;captionTrim?:number;note?:string};

export type PoseRectMap = Record<PoseId,PoseRectSpec>;

export interface BackgroundRemovalConfig {
  threshold:number;
  edgeConnected:boolean;
  feather:number;
  preserveInteriorBlack:true;
}

export interface CharacterSheetProfile {
  fighterId:string;
  sourceTexture:string;
  sourceFile:string;
  layout:'5x6'|'6x5'|'manual-irregular';
  poses:PoseRectMap;
  captionTrim?:number;
  backgroundRemoval?:BackgroundRemovalConfig;
}

/** Runtime path for this build uses the pre-extracted PNGs generated by scripts/extract_poses.py. */
export interface ExtractedPoseTexture {
  poseId:number;
  textureKey:string;
  path:string;
}
