/**
 * Which skill-sheet cells each fighter has.
 *
 * GENERATED by `scripts/gen-skill-cells.mjs` from
 * `audit/skill-assets/skill-asset-manifest.json`. Do not edit by hand — rerun
 * `npm run assets:skills:codegen` after regenerating the art.
 *
 * Cells are letters because the source sheets are grids and the pipeline names
 * them by position. What each letter *is* differs per fighter — `A`-`C` are
 * always the three charge frames and `D` the release, but past that a cell may be
 * a pose, a standalone effect layer, or in blade's case a weapon split out of a
 * larger cell. `src/fighters/ultimateVisuals.ts` and `installPoses.ts` are where
 * the meaning is assigned.
 *
 * 226 cells across 12 fighters.
 */
export const SKILL_CELLS: Record<string, readonly string[]> = {
  alien: ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P'],
  blade: ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'K_weapon_blue', 'K_weapon_black'],
  doge: ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R'],
  goblin: ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W'],
  ok: ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U'],
  pink: ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W'],
  salad: ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'L2', 'M2', 'N2', 'O2', 'P'],
  sauce: ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O'],
  scared: ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V'],
  tempura: ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P'],
  wizard: ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R'],
  ya: ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N'],
};
