import Phaser from 'phaser';import {FIGHTERS} from '../data/fighterData';import {SPECIAL_H_BY_ID} from '../data/specialHData';import type {GameMode,MatchSetup} from '../systems/GameState';import {audio} from '../systems/AudioManager';
export class CharacterSelectScene extends Phaser.Scene{
 private idx=0;private phase:1|2=1;private p1='';private cells:Phaser.GameObjects.Container[]=[];private info!:Phaser.GameObjects.Text;private prompt!:Phaser.GameObjects.Text;private mode!:GameMode;
 constructor(){super('CharacterSelectScene');}
 create(){this.mode=this.registry.get('mode')??'cpu';this.cameras.main.setBackgroundColor('#080808');this.add.text(640,42,'CHOOSE YOUR CURSED FIGHTER',{fontFamily:'Impact',fontSize:'42px',color:'#ffe45c'}).setOrigin(.5);
  const startX=125,startY=130,cw=220,ch=155;FIGHTERS.forEach((f,i)=>{const col=i%4,row=Math.floor(i/4);const x=startX+col*250,y=startY+row*175;const c=this.add.container(x,y);const border=this.add.rectangle(0,0,cw,ch,0x111111,.9).setStrokeStyle(3,0x555555);const thumb=this.add.image(-65,0,`card-${f.id}`).setDisplaySize(82,120);const nm=this.add.text(-10,-42,f.shortName,{fontFamily:'Impact',fontSize:'19px',color:'#fff',wordWrap:{width:112}});const role=this.add.text(-10,-8,f.archetype,{fontFamily:'monospace',fontSize:'11px',color:'#a9a9a9',wordWrap:{width:112}});const rate=this.add.text(-10,36,`HP ${f.ratings.hp}  ATK ${f.ratings.attack}\nSPD ${f.ratings.speed} RNG ${f.ratings.range} CTL ${f.ratings.control}`,{fontFamily:'monospace',fontSize:'11px',color:'#d6bcff'});c.add([border,thumb,nm,role,rate]);c.setSize(cw,ch).setInteractive(new Phaser.Geom.Rectangle(-cw/2,-ch/2,cw,ch),Phaser.Geom.Rectangle.Contains).on('pointerdown',()=>{this.idx=i;this.confirm()});this.cells.push(c);});
  this.info=this.add.text(640,650,'',{fontFamily:'monospace',fontSize:'14px',color:'#fff',align:'center'}).setOrigin(.5);this.prompt=this.add.text(640,603,'',{fontFamily:'Impact',fontSize:'25px',color:'#ffe45c'}).setOrigin(.5);this.render();
  const kb=this.input.keyboard!;kb.on('keydown-W',()=>this.phase===1&&this.move(-4));kb.on('keydown-UP',()=>this.phase===2&&this.move(-4));kb.on('keydown-S',()=>this.phase===1&&this.move(4));kb.on('keydown-DOWN',()=>this.phase===2&&this.move(4));kb.on('keydown-A',()=>this.phase===1&&this.move(-1));kb.on('keydown-LEFT',()=>this.phase===2&&this.move(-1));kb.on('keydown-D',()=>this.phase===1&&this.move(1));kb.on('keydown-RIGHT',()=>this.phase===2&&this.move(1));kb.on('keydown-F',()=>{if(this.phase===1)this.confirm()});kb.on('keydown-J',()=>{if(this.phase===2)this.confirm()});kb.on('keydown-G',this.back,this);kb.on('keydown-ESC',this.back,this);this.events.once('shutdown',()=>kb.removeAllListeners());
 }
 move(d:number){this.idx=(this.idx+d+12)%12;audio.beep('menu');this.render();}
 render(){this.cells.forEach((c,i)=>{const r=c.list[0] as Phaser.GameObjects.Rectangle;r.setStrokeStyle(i===this.idx?5:3,i===this.idx?0xffdf4f:0x555555);c.setScale(i===this.idx?1.05:1);if(i===this.idx&&Math.random()<.2)c.x+=Phaser.Math.Between(-2,2)});const f=FIGHTERS[this.idx];const skills=[`H ${SPECIAL_H_BY_ID[f.id].displayName}`,`236 ${f.special1.name}`,`214 ${f.special2.name}`,f.special3?`623 ${f.special3.name}`:'',`22 ${f.functionMove.name}`,`ULT ${f.ultimate.name}`].filter(Boolean).join('   |   ');this.info.setText(skills);this.prompt.setText(this.phase===1?'P1 SELECT  — WASD + F':`P2 SELECT — ARROWS + J   (P1: ${FIGHTERS.find(x=>x.id===this.p1)?.shortName})`);}
 confirm(){const f=FIGHTERS[this.idx];audio.beep('menu');if(this.phase===1){this.p1=f.id;if(this.mode==='local'){this.phase=2;this.idx=(this.idx+1)%12;this.render();return;}let p2;if(this.mode==='training')p2=FIGHTERS[(this.idx+1)%12].id;else {const choices=FIGHTERS.filter(x=>x.id!==this.p1);p2=choices[Math.floor(Math.random()*choices.length)].id;}this.go(p2);}else this.go(f.id);}
 go(p2:string){const setup:MatchSetup={mode:this.mode,p1:this.p1,p2,difficulty:this.registry.get('difficulty')??'NORMAL'};this.registry.set('matchSetup',setup);this.scene.start('VsScene',{setup});}
 back(){if(this.phase===2){this.phase=1;this.idx=Math.max(0,FIGHTERS.findIndex(x=>x.id===this.p1));this.render();}else this.scene.start('ModeSelectScene');}
}
