import Phaser from 'phaser';import type {GameMode} from '../systems/GameState';import {audio} from '../systems/AudioManager';
export class ModeSelectScene extends Phaser.Scene{
 private index=0;private diff=1;private items=['1P VS CPU','2P LOCAL','TRAINING'];private diffs=['EASY','NORMAL','HARD'] as const;private texts:Phaser.GameObjects.Text[]=[];private diffText!:Phaser.GameObjects.Text;
 constructor(){super('ModeSelectScene');}
 create(){this.cameras.main.setBackgroundColor('#090909');this.add.text(640,92,'SELECT MODE',{fontFamily:'Impact',fontSize:'62px',color:'#ffe45c'}).setOrigin(.5);this.items.forEach((x,i)=>this.texts.push(this.add.text(640,230+i*100,x,{fontFamily:'Impact',fontSize:'42px',color:'#ffffff',stroke:'#000',strokeThickness:6}).setOrigin(.5).setInteractive().on('pointerdown',()=>{this.index=i;this.confirm()})));this.diffText=this.add.text(640,555,'CPU: NORMAL',{fontFamily:'monospace',fontSize:'22px',color:'#aabfff'}).setOrigin(.5);this.add.text(640,650,'W/S or ↑/↓ SELECT   A/D or ←/→ DIFFICULTY   F/J/ENTER CONFIRM   G/ESC BACK',{fontFamily:'monospace',fontSize:'15px',color:'#777'}).setOrigin(.5);this.render();
  const kb=this.input.keyboard!;kb.on('keydown-W',this.up,this);kb.on('keydown-UP',this.up,this);kb.on('keydown-S',this.down,this);kb.on('keydown-DOWN',this.down,this);kb.on('keydown-A',this.left,this);kb.on('keydown-LEFT',this.left,this);kb.on('keydown-D',this.right,this);kb.on('keydown-RIGHT',this.right,this);kb.on('keydown-F',this.confirm,this);kb.on('keydown-J',this.confirm,this);kb.on('keydown-ENTER',this.confirm,this);kb.on('keydown-ESC',()=>this.scene.start('TitleScene'));this.events.once('shutdown',()=>kb.removeAllListeners());
 }
 up(){this.index=(this.index+this.items.length-1)%this.items.length;audio.beep('menu');this.render()}down(){this.index=(this.index+1)%this.items.length;audio.beep('menu');this.render()}left(){this.diff=(this.diff+2)%3;this.render()}right(){this.diff=(this.diff+1)%3;this.render()}
 render(){this.texts.forEach((t,i)=>t.setColor(i===this.index?'#ffe45c':'#ffffff').setScale(i===this.index?1.08:1));this.diffText.setText(`CPU: ${this.diffs[this.diff]}`).setVisible(this.index===0);}
 confirm(){const mode:GameMode=this.index===0?'cpu':this.index===1?'local':'training';this.registry.set('mode',mode);this.registry.set('difficulty',this.diffs[this.diff]);audio.beep('menu');this.scene.start('CharacterSelectScene');}
}
