import fs from 'node:fs';
import path from 'node:path';
import assert from 'node:assert/strict';
const root=process.cwd();const read=p=>fs.readFileSync(path.join(root,p),'utf8');
const ids=['alien','doge','ya','tempura','goblin','salad','wizard','blade','pink','sauce','scared','ok'];
const names=['逼逼逼動感光波','超級賽狗','哈ㄗ咖西','oh fucking 天婦羅尬哩涼！','長老您保重','菜就多練','喵蘇魯的召喚！','汪爆氣流斬','派甜心假面...露出','胡渣男！','嗷嗷嗷嗷嗷！！','大哥你是了解我的'];
const legacyNames=['地球全頻掃描','Much Power','社死大頭貼','企鵝軍團','OH FUCKING 企鵝軍團','十年壽命換高顏值','巨無霸沙拉盆墜擊','克蘇魯喵喵的召喚','超巨雙刀聖裁','真臉降臨','胡渣蘸醬大暴走','惡夢來襲','OK 審判'];
const fighterData=read('src/data/fighterData.ts'),fighter=read('src/fighters/Fighter.ts'),combat=read('src/combat/CombatSystem.ts'),ultimate=read('src/combat/UltimateAttack.ts'),defs=read('src/data/ultimateDefinitions.ts'),hData=read('src/data/specialHData.ts'),hCtrl=read('src/combat/ChargeableSpecialH.ts'),meme=read('src/combat/UltimateInputState.ts'),cutin=read('src/combat/UltimateCutInManager.ts'),player=read('src/controllers/PlayerController.ts'),cpu=read('src/controllers/CPUController.ts'),battle=read('src/scenes/BattleScene.ts'),loader=read('src/systems/SkillAssetLoader.ts'),select=read('src/scenes/CharacterSelectScene.ts'),hud=read('src/ui/BattleHUD.ts'),move=read('src/combat/MoveData.ts'),states=read('src/fighters/FighterState.ts');
const pkg=JSON.parse(read('package.json'));const baseAudit=JSON.parse(read('audit/asset-audit.json'));const profiles=JSON.parse(read('audit/sheet-profiles.json'));const skillManifest=JSON.parse(read('audit/skill-assets/skill-asset-manifest.json'));const skillValidation=JSON.parse(read('audit/skill-assets/validation.json'));
// Existing healthy base-pose pipeline stays intact.
assert.equal(baseAudit.filesFound,12);assert.equal(baseAudit.warnings.length,0);assert.equal(Object.keys(profiles).length,12);assert.equal(Object.values(profiles).reduce((n,p)=>n+Object.keys(p.poses).length,0),360);
for(const id of ids){assert.match(fighterData,new RegExp(`id:'${id}'`));assert.equal(fs.readdirSync(path.join(root,'public/assets/poses',id)).filter(x=>x.endsWith('.png')).length,30,`${id}: base 30 poses`);}
assert.equal(skillValidation.stats.files,226);assert.equal(skillValidation.stats.rgba,226);assert.equal(skillValidation.stats.transparent,226);assert.equal(skillValidation.stats.gridLineWarnings,0);assert.equal(skillValidation.stats.edgeOpaqueWarnings,0);assert.equal(skillValidation.stats.basePoseRegression,0);assert.equal(skillValidation.stats.missing,0);assert.equal(skillValidation.stats.backgrounds,12);assert.equal(skillValidation.warningCount,0);
assert.equal(Object.keys(skillManifest.fighters).length,12);assert.equal(Object.values(skillManifest.fighters).reduce((n,r)=>n+r.assets.length,0),224);assert.equal(skillManifest.fighters.blade.derivedAssets.length,2);assert.equal(Object.keys(skillManifest.backgrounds).length,12);
for(const id of ids){for(const a of skillManifest.fighters[id].assets){assert.ok(fs.existsSync(path.join(root,a.outputPath)),a.outputPath);}assert.ok(fs.existsSync(path.join(root,skillManifest.backgrounds[id].outputPath)));assert.match(loader,new RegExp(`ultimate-bg-\\$\\{fid\\}`));}
// Input precedence and logical Special-H. P1 H / P2 L, P1 T / P2 I.
assert.match(player,/special:'H'/);assert.match(player,/special:'L'/);assert.match(player,/ultimate:'T'/);assert.match(player,/ultimate:'I'/);assert.match(player,/chord\('heavy','special'\)/);assert.match(player,/chord\('light','special'\)/);assert.match(player,/CommandParser\.command\(this\.buffer,\[6,2,3\]/);assert.match(player,/CommandParser\.command\(this\.buffer,\[2,1,4\]/);assert.match(player,/CommandParser\.command\(this\.buffer,\[2,2\]/);assert.match(player,/CommandParser\.command\(this\.buffer,\[2,3,6\]/);assert.match(player,/action='specialH'/);
const precedence=['impact','parry','special3','special2','function','special1','specialH'].map(x=>player.indexOf(`'${x}'`));for(let i=1;i<precedence.length;i++)assert.ok(precedence[i]>precedence[i-1],`input precedence ${i}`);
assert.match(cpu,/shouldUltimate/);assert.match(cpu,/action='ultimate'/);assert.doesNotMatch(cpu,/ultimateHeld\s*=\s*true/);
// H controller: 0.4 / 0.9 / 1.5 cap semantics, release-only, no cooldown.
assert.match(states,/H_CHARGING/);assert.match(states,/H_SPECIAL/);assert.match(hCtrl,/s\.frames<24\?1:s\.frames<54\?2:3/);assert.match(hCtrl,/intent\.specialReleased/);assert.doesNotMatch(hCtrl,/COOLDOWN|cooldown/i);assert.doesNotMatch(hData,/cooldown/i);assert.doesNotMatch(hData,/interface ChargeableSpecialDefinition[^}]*cooldown/s);assert.match(hCtrl,/s\.phase='IDLE'/);
for(const n of ['斷訊掃描波','肌肉衝撞','尷尬招呼波','企鵝衝隊','愛的擁抱','拒吃震波','JPEG 魔法陣','鈍刀蓄斬','尖叫爆震','黏醬飛射','驚嚇衝撞','OK 判決波'])assert.ok(hData.includes(n),n);
assert.match(hData,/base\('h-scared-1'[^\n]*,120,120,/);assert.match(hData,/base\('h-scared-2'[^\n]*,180,190,/);assert.match(hData,/base\('h-scared-3'[^\n]*,250,280,/);assert.match(fighter,/move\.sourceSkill==='SPECIAL_H'/);assert.match(fighter,/this\.x\+=dir\*/);
// Meme player protocol and external meter readiness/cancellation.
for(const st of ['MEME_IDLE','MEME_CHARGING','MEME_READY_WAIT_RELEASE','MEME_READY_WAIT_PRESS','ULTIMATE_CUTIN','ULTIMATE_GAMEPLAY'])assert.ok(meme.includes(st));assert.match(meme,/gainMeter\(5\/60\)/);assert.match(meme,/intent\.ultimateReleased/);assert.match(meme,/intent\.ultimatePressed/);assert.match(meme,/syncAfterExternalMeterChange/);assert.match(meme,/f\.meter<100&&this\.state\.startsWith\('MEME_READY'\)/);
assert.match(battle,/instanceof PlayerController&&this\.ult1\.tick/);assert.match(battle,/instanceof PlayerController&&this\.ult2\.tick/);assert.match(battle,/CPUController/);assert.match(battle,/spendMeter\(100\)/);
// Cut-in is presentation-only and Scene time continues while fixed combat simulation pauses.
assert.match(battle,/if\(!this\.cutIn\?\.isActive\)this\.clock\.advance/);assert.doesNotMatch(cutin,/takeHit|takeThrown|damage\s*[:=]|startUltimate/);assert.match(cutin,/scene\.tweens\.add/);assert.match(cutin,/delayedCall/);assert.match(cutin,/voiceText/);assert.match(cutin,/ultimateName/);assert.match(battle,/this\.cutIn\.start/);assert.match(battle,/this\.combat\.startUltimate/);
// Old mixed Ultimate pattern schema is gone.
assert.doesNotMatch(move,/UltimatePattern|pattern:/);assert.doesNotMatch(fighterData,/beamSweep|installBurst|socialSqueeze|penguinApocalypse|fullscreenThrow|tableFlip|magicRitual|rushSequence|starBreakdown|sauceRush|panicBurst/);assert.doesNotMatch(ultimate,/case\s*'beamSweep'|case\s*'installBurst'|case\s*'penguinApocalypse'/);
for(const n of names){assert.ok(defs.includes(n),`missing official name ${n}`);assert.ok(fighterData.includes(n),`fighterData name ${n}`);}for(const n of legacyNames){assert.ok(!fighterData.includes(n),`legacy player-facing name ${n}`);assert.ok(!select.includes(n),`legacy select name ${n}`);assert.ok(!hud.includes(n),`legacy hud name ${n}`);}assert.doesNotMatch(defs,/gameplayUltimateName|cutInName|displayUltimateName/);
// Gameplay runtime modules, render capture, summons, capture and cleanup.
for(const id of ['ALIEN_SCAN_RUNTIME','DOGE_INSTALL_RUNTIME','YA_PHOTO_RUNTIME','PENGUIN_CLONE_RUNTIME','GOBLIN_INSTALL_RUNTIME','SALAD_BOWL_RUNTIME','CTHULHU_RUNTIME','DUAL_SWORD_RUNTIME','REAL_FACE_RUNTIME','SAUCE_RAMPAGE_RUNTIME','HUSKY_RUNTIME','OK_CAPTURE_RUNTIME'])assert.ok(defs.includes(id)&&fighterData.includes(id),id);
assert.match(ultimate,/add\.renderTexture/);assert.match(ultimate,/this\.rt\?\.destroy/);assert.match(ultimate,/new SummonEntity/);assert.match(ultimate,/MIRROR_PLAYER_INPUT/);assert.match(ultimate,/kind,'HUSKY'|,'HUSKY'/);assert.match(ultimate,/captureLock/);assert.match(ultimate,/CAPTURE MISS/);assert.doesNotMatch(ultimate,/this\.foe\.hp\s*[-+]=/);assert.doesNotMatch(ultimate,/enemy\.hp\s*[-+]=/);
assert.match(combat,/takeSummonHits/);assert.match(combat,/contactPoint/);assert.match(combat,/new UltimateAttack\(this\.scene,owner,move,foe\)/);
// Install 2x is real fighter scale, feet-baseline origin, sockets and restore; dual sword assets are independent derivatives.
assert.match(fighter,/DOGE_MUCH_POWER'\?\.90:1/);assert.match(hCtrl,/skill-goblin-q/);assert.match(combat,/h-sauce-ground'[\s\S]*statusMoveMultipliers\.set\('slow'/);assert.match(battle,/blade-install-f/);assert.match(battle,/blade-install-g/);assert.match(battle,/pink-real-slap/);assert.match(battle,/pink-real-belly/);assert.match(ultimate,/private pinkTimeline/);assert.match(ultimate,/show\('H'[\s\S]*show\('I'[\s\S]*enterInstall\('REAL_FACE'/);assert.match(cutin,/add\.triangle/);
assert.match(fighter,/const scale=this\.baseScale\*\(this\.installType\?2:1\)/);assert.match(fighter,/hurtbox\(\)[\s\S]*if\(this\.installType\)\{w\*=2;h\*=2;\}/);assert.match(fighter,/setOrigin\(\.5,1\)/);assert.match(fighter,/leftWeaponSocket/);assert.match(fighter,/rightWeaponSocket/);assert.match(fighter,/exitInstall\(\)/);assert.match(ultimate,/skill-blade-k_weapon_blue/);assert.match(ultimate,/skill-blade-k_weapon_black/);assert.match(loader,/K_weapon_blue\.png/);assert.match(loader,/K_weapon_black\.png/);
// UI surfaces logical H and Ready state.
assert.match(select,/SPECIAL_H_BY_ID/);assert.match(select,/`H \$\{SPECIAL_H_BY_ID/);assert.match(hud,/MEME READY/);
// Exact user-specified voice hooks exist even if files are absent.
for(const v of ['ult_alien_voice','ult_doge_voice','ult_ya_voice','ult_penguin_voice','ult_goblin_voice','ult_salad_voice','ult_orange_cat_voice','ult_swordshield_voice','ult_pinkstar_voice','ult_sauce_dog_voice','ult_scared_cat_voice','ult_okboss_voice'])assert.ok(defs.includes(v),v);
// Project contract remains Phaser/Vite; package scripts can add skill pipeline without replacing build.
assert.equal(pkg.scripts.build,'tsc --noEmit && vite build');assert.equal(pkg.dependencies.phaser,'^3.90.0');
for(const dir of ['src','scripts'])for(const file of fs.readdirSync(path.join(root,dir),{recursive:true}).filter(x=>typeof x==='string'&&/\.(ts|mjs|py)$/.test(x)&&x!=='static-qa.mjs')){const text=read(path.join(dir,file));assert.doesNotMatch(text,/\b(TODO|FIXME|placeholder implementation|Coming Soon|future work|omitted|stub)\b/i,`${file} contains unfinished marker`);}
console.log('STATIC QA PASS');
console.log('12 fighters / 360 base poses unchanged / 224 source skill cells + 2 derived dual-sword modules / 12 backgrounds / H+Meme+Cut-in+Runtime+Install checks verified.');
